# Generated by Django 5.1.4 on 2025-03-18 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_product_auction_duration_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='auction_duration_hours',
        ),
        migrations.AddField(
            model_name='product',
            name='auction_duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/images/default.jpg', upload_to='uploads/images'),
        ),
    ]
